DROP TABLE IF EXISTS `wp_huge_itslider_images`;
CREATE TABLE `wp_huge_itslider_images` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `slider_id` varchar(200) DEFAULT NULL,
  `description` text,
  `image_url` text,
  `sl_url` varchar(128) DEFAULT NULL,
  `sl_type` text NOT NULL,
  `link_target` text NOT NULL,
  `sl_stitle` text NOT NULL,
  `sl_sdesc` text NOT NULL,
  `sl_postlink` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` tinyint(4) unsigned DEFAULT NULL,
  `published_in_sl_width` tinyint(4) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
LOCK TABLES `wp_huge_itslider_images` WRITE;
INSERT INTO `wp_huge_itslider_images` VALUES ('1','','1','','http://wordpress.local/wp-content/plugins/slider-image/Front_images/slides/slide1.jpg','http://huge-it.com','image','on','','','','1','1',''), ('2','Simple Usage','1','','http://wordpress.local/wp-content/plugins/slider-image/Front_images/slides/slide2.jpg','http://huge-it.com','image','on','','','','2','1',''), ('3','Huge-IT Slider','1','The slider allows having unlimited amount of images with their titles and descriptions. The slider uses autogenerated shortcodes making it easier for the users to add it to the custom location.','http://wordpress.local/wp-content/plugins/slider-image/Front_images/slides/slide3.jpg','http://huge-it.com','image','on','','','','3','1','');
UNLOCK TABLES;
